services:
  db:
    image: postgres:16
    container_name: miniSpotify_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: miniSpotifydb
      POSTGRES_USER: miniSpotifyuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - miniSpotify_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniSpotifyuser -d miniSpotifydb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  miniSpotify_data: